### ISSUE TITLE
 Product Request Error : woocommerce_product_image_upload_error:Error getting remote image

### ISSUE THREAD

**Issue by salimsaid** [woocommerce/woocommerce-rest-api#242] opened 2020-09-05 14:26 UTC
Am calling the api to import products into my store, woocommerce returns the following error

![shopmaster error forbidden](https://user-images.githubusercontent.com/5766809/92307144-d70b4c80-ef9c-11ea-82f1-b8c2c33fb6c6.PNG)
![shopmaster not found](https://user-images.githubusercontent.com/5766809/92307146-d8d51000-ef9c-11ea-9c1a-89843752174d.PNG)

What could i be missing ? My vps is not blocking any outgoing requests.

**Comment by vedanshujain** [comment] 2020-10-27 10:28
Based on the error looks like the store does not have access to those links. To debug, I'd recommend logging onto the server and try accessing those links directly using a `curl` or `wget` command (for linux servers) to see if you can reproduce the error. Perhaps you can get better support by asking around in [community forums](https://wordpress.org/support/plugin/woocommerce/). 

That said, I am closing the issue because this does not looks like a WooCommerce core bug and is not reproducible. But feel free to reply back incase I have missed something or you want to discuss further.

**Closed as completed by vedanshujain** 2020-10-27 10:28 UTC
