### ISSUE TITLE
"total_sales" field in the GET v3/products response is of type string instead of integer for some products

### ISSUE THREAD

**Issue by chrisbbe** [woocommerce/woocommerce-rest-api#130] opened 2020-02-08 21:52 UTC
Hi,

I'm running WooCommerce version 3.9.1 and WooCommerce REST API package version 1.0.7.

I created a new product as a draft (never published), then the response from GET v3/products represented the product in the list with field **total_sales** with a value **"0".** According to the API documentation, this field should be of type integer causing my JSON marshaling to fail.

All other products have the data type **integer** for the field. I assume this is a bug?

Attached is the response snippet containing the failing product:

```
  {
    "id": 28458,
    "name": "@@@@@",
    "slug": "",
    "permalink": "https:\/\/@@@@",
    "date_created": null,
    "date_created_gmt": null,
    "date_modified": "2020-02-08T21:03:51",
    "date_modified_gmt": "2020-02-08T20:03:51",
    "type": "simple",
    "status": "draft",
    "featured": false,
    "catalog_visibility": "visible",
    "description": "@@",
    "short_description": "",
    "sku": "",
    "price": "",
    "regular_price": "",
    "sale_price": "",
    "date_on_sale_from": null,
    "date_on_sale_from_gmt": null,
    "date_on_sale_to": null,
    "date_on_sale_to_gmt": null,
    "price_html": "",
    "on_sale": false,
    "purchasable": false,
    "total_sales": "0",
    "virtual": false,
    "downloadable": false,
    "downloads": [],
    "download_limit": -1,
    "download_expiry": -1,
    "external_url": "",
    "button_text": "",
    "tax_status": "taxable",
    "tax_class": "",
    "manage_stock": false,
    "stock_quantity": null,
    "stock_status": "instock",
    "backorders": "no",
    "backorders_allowed": false,
    "backordered": false,
    "sold_individually": false,
    "weight": "",
    "dimensions": {
      "length": "",
      "width": "",
      "height": ""
    },
    "shipping_required": true,
    "shipping_taxable": true,
    "shipping_class": "",
    "shipping_class_id": 0,
    "reviews_allowed": true,
    "average_rating": "0.00",
    "rating_count": 0,
    "related_ids": [],
    "upsell_ids": [],
    "cross_sell_ids": [],
    "parent_id": 0,
    "purchase_note": "",
    "categories": [],
    "tags": [],
    "images": [],
    "attributes": [],
    "default_attributes": [],
    "variations": [],
    "grouped_products": [],
    "menu_order": 0,
    "meta_data": [],
    "_links": {
      "self": [
        {
          "href": "https:\/\/@@@"
        }
      ],
      "collection": [
        {
          "href": "https:\/\/@@@"
        }
      ]
    }
  },
```

**Comment by juliaamosova** [comment] 2020-03-18 21:33
Hi @chrisbbe,

Apologies for the delayed response! Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. Tested with WooCommerce 4.0. 

My product in the `draft` status:

![draft1](https://user-images.githubusercontent.com/19143190/77009422-46817700-693e-11ea-9213-67981b462e08.jpg)

My GET request for that draft product shows `total_sales` response type integer:

![draft2](https://user-images.githubusercontent.com/19143190/77009466-5ac57400-693e-11ea-9972-a606256a46e6.jpg)

Can you please confirm if you are still experiencing issues? If so, please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by vedanshujain** [comment] 2020-09-02 11:25
I am closing this issue as part of the repo maintenance, but feel free to write back if you have any additional comments.

**Closed by vedanshujain** 2020-09-02 11:25 UTC
Labels: can't reproduce, status: needs feedback

**Comment by akfaew** [comment] 2023-07-21 04:23
I can confirm the issue, out of 500 products, for two the total_sales is a string of value "0"

**Comment by joaofrf** [comment] 2024-06-19 12:35
Same happened to me, out of my 8 products I had 1 where total_sales is a string instead of integer
Does anyone have any clue/fix for this?
