### ISSUE TITLE
Update the order status, error 404 is appearing

### ISSUE THREAD

**Issue by thivapraba** [woocommerce/woocommerce-rest-api#245] opened 2020-09-25 14:34 UTC
I am trying to update the order status through Woocommerce REST API but i egt 404 error and could not archieve this even via Postman.
I am using Axios to perform request in VUE.js.
I could not realize in which part I am doing wrong.

This is my request
` axios.put('https://staging/wp-json/wc/v3/orders/1977/consumer_key=123&consumer_secret=456', {status: "completed"});`

Any suggestions please...

**Comment by vedanshujain** [comment] 2020-10-27 10:45
The issue is before `consumer_key` it should be `?` and not a `/` since consumer key are params and not part of the URL. So your URL should be `https://staging/wp-json/wc/v3/orders/1977?consumer_key=123&consumer_secret=456`.

Closing the issue, but feel free to reply back if it does not solve it, or there are more errors.

**Closed as completed by vedanshujain** 2020-10-27 10:45 UTC
