### ISSUE TITLE
Create product api issue in title if i am using & in title

### ISSUE THREAD

**Issue by pradeepgadiya** [woocommerce/woocommerce-rest-api#244] opened 2020-09-17 07:02 UTC
i want to create a product through API and using in title & sign like shoes & sandals .
title proper showing all product listing but once i open this product i was showing title in decode form like this shoes & sandals.
I want my title like this shoes & sandals.

can you please suggest me how can i use & symbol in api?
Thanks

**Comment by vedanshujain** [comment] 2020-10-27 10:43
You are seeing the decoded title in edit view, but for the customer `&` will be shown as it is, so it's only you (and other admins) who is seeing the decoded version, but customers on your site will see what you intended. Unfortunately this is a [WordPress core issue](https://core.trac.wordpress.org/ticket/11311) and not a WooCommerce one, and we won't be able to tell when it will be fixed.

Note that `&` in titles is generally not recommended for SEO reasons.

Closing since the issue is upstream.

**Closed as completed by vedanshujain** 2020-10-27 10:43 UTC
Labels: wordpress
